import type { CardDef, Domain, LegendAbility } from "./types";

export const DOMAINS: Record<
  Domain,
  { label: string; hex: string; token: string }
> = {
  fury: { label: "Fury", hex: "#c44536", token: "var(--domain-fury)" },
  calm: { label: "Calm", hex: "#3d8c5e", token: "var(--domain-calm)" },
  mind: { label: "Mind", hex: "#3d6eb8", token: "var(--domain-mind)" },
  body: { label: "Body", hex: "#c46b2d", token: "var(--domain-body)" },
  chaos: { label: "Chaos", hex: "#7b4bb8", token: "var(--domain-chaos)" },
  order: { label: "Order", hex: "#c9b48a", token: "var(--domain-order)" },
};

export interface LegendInfo {
  id: string;
  name: string;
  title: string;
  domains: Domain[];
  ability: LegendAbility;
  abilityText: string;
  championId: string;
  battlefieldId: string;
  art: string;
  blurb: string;
  product: string;
}

export const LEGENDS: LegendInfo[] = [
  {
    id: "jinx",
    name: "Jinx",
    title: "Loose Cannon",
    domains: ["fury", "chaos"],
    ability: "jinx",
    abilityText: "Once per turn: Recycle a rune to deal 1 damage to a unit.",
    championId: "jinx-champ",
    battlefieldId: "dragon",
    art: "/art/cards/legend-jinx.jpg",
    blurb: "Origins Champion Deck. Aggro — rockets, cheap units, first conquests.",
    product: "Origins Champion Deck",
  },
  {
    id: "ahri",
    name: "Ahri",
    title: "Nine-Tailed Fox",
    domains: ["calm", "mind"],
    ability: "ahri",
    abilityText:
      "Once per turn: Exhaust your legend and a rune to return an enemy unit to base.",
    championId: "ahri-champ",
    battlefieldId: "abyss",
    art: "/art/cards/legend-ahri.jpg",
    blurb: "Origins constructed. Control — charm threats and out-draw the table.",
    product: "Origins",
  },
  {
    id: "darius",
    name: "Darius",
    title: "Hand of Noxus",
    domains: ["fury", "order"],
    ability: "darius",
    abilityText: "The first unit you play each turn costs 1 less energy.",
    championId: "darius-champ",
    battlefieldId: "baron",
    art: "/art/cards/legend-darius.jpg",
    blurb: "Origins constructed. Midrange smash — efficient bodies and executes.",
    product: "Origins",
  },
  {
    id: "garen",
    name: "Garen",
    title: "Might of Demacia",
    domains: ["body", "order"],
    ability: "garen",
    abilityText:
      "Once per turn: Ready a friendly unit at a battlefield you control.",
    championId: "garen-champ",
    battlefieldId: "nexus",
    art: "/art/cards/legend-garen.jpg",
    blurb: "Proving Grounds. Hold — fat units and a legend that re-arms defenders.",
    product: "Proving Grounds",
  },
  {
    id: "viktor",
    name: "Viktor",
    title: "Herald of the Arcane",
    domains: ["mind", "order"],
    ability: "viktor",
    abilityText: "Once per turn: put a 1-Might Recruit into your base.",
    championId: "viktor-champ",
    battlefieldId: "nexus",
    art: "/art/viktor.jpg",
    blurb: "Origins Champion Deck. Swarm — expendable Recruits, then pick the board apart.",
    product: "Origins Champion Deck",
  },
  {
    id: "leesin",
    name: "Lee Sin",
    title: "Blind Monk",
    domains: ["calm", "body"],
    ability: "leesin",
    abilityText: "Once per turn: Exhaust and pay 1 energy. A friendly unit gets +1 Might.",
    championId: "leesin-champ",
    battlefieldId: "abyss",
    art: "/art/leesin.jpg",
    blurb: "Origins Champion Deck. Midrange buffs — small bodies become hard fights.",
    product: "Origins Champion Deck",
  },
  {
    id: "annie",
    name: "Annie",
    title: "Dark Child",
    domains: ["fury", "chaos"],
    ability: "annie",
    abilityText: "Once per turn: Exhaust your legend to ready two runes.",
    championId: "annie-champ",
    battlefieldId: "dragon",
    art: "/art/annie.jpg",
    blurb: "Proving Grounds. Burn — ready runes, then Tibbers and incinerate the lane.",
    product: "Proving Grounds",
  },
  {
    id: "lux",
    name: "Lux",
    title: "Lady of Luminosity",
    domains: ["mind", "order"],
    ability: "lux",
    abilityText: "When you cast a spell costing 3 or more, draw 1.",
    championId: "lux-champ",
    battlefieldId: "baron",
    art: "/art/lux.jpg",
    blurb: "Proving Grounds. Spell value — expensive light magic refills your hand.",
    product: "Proving Grounds",
  },
];

const CARDS: CardDef[] = [
  // Legends
  {
    id: "legend-jinx",
    name: "Jinx, Loose Cannon",
    kind: "legend",
    domains: ["fury", "chaos"],
    energy: 0,
    power: 0,
    text: "Once per turn: Recycle a rune to deal 1 damage to a unit.",
    art: "/art/cards/legend-jinx.jpg",
    legendAbility: "jinx",
  },
  {
    id: "legend-ahri",
    name: "Ahri, Nine-Tailed Fox",
    kind: "legend",
    domains: ["calm", "mind"],
    energy: 0,
    power: 0,
    text: "Once per turn: Exhaust your legend and a rune to recall an enemy unit.",
    art: "/art/cards/legend-ahri.jpg",
    legendAbility: "ahri",
  },
  {
    id: "legend-darius",
    name: "Darius, Hand of Noxus",
    kind: "legend",
    domains: ["fury", "order"],
    energy: 0,
    power: 0,
    text: "The first unit you play each turn costs 1 less energy.",
    art: "/art/cards/legend-darius.jpg",
    legendAbility: "darius",
  },
  {
    id: "legend-garen",
    name: "Garen, Might of Demacia",
    kind: "legend",
    domains: ["body", "order"],
    energy: 0,
    power: 0,
    text: "Once per turn: Ready a friendly unit at a battlefield you control.",
    art: "/art/cards/legend-garen.jpg",
    legendAbility: "garen",
  },

  // Champions
  {
    id: "jinx-champ",
    name: "Jinx, Supercharged",
    kind: "unit",
    domains: ["fury", "chaos"],
    energy: 5,
    power: 1,
    might: 5,
    text: "Assault 2. Champion — play from your champion zone.",
    art: "/art/cards/jinx-champ.jpg",
    assault: 2,
    isChampion: true,
  },
  {
    id: "ahri-champ",
    name: "Ahri, Vastaya",
    kind: "unit",
    domains: ["calm", "mind"],
    energy: 4,
    power: 1,
    might: 4,
    text: "When you conquer, draw 1. Champion.",
    art: "/art/cards/ahri-champ.jpg",
    onConquer: { type: "draw", n: 1 },
    isChampion: true,
  },
  {
    id: "darius-champ",
    name: "Darius, Noxian Might",
    kind: "unit",
    domains: ["fury", "order"],
    energy: 6,
    power: 1,
    might: 7,
    text: "Assault 1. Champion.",
    art: "/art/cards/darius-champ.jpg",
    assault: 1,
    isChampion: true,
  },
  {
    id: "garen-champ",
    name: "Garen, Demacian",
    kind: "unit",
    domains: ["body", "order"],
    energy: 5,
    power: 1,
    might: 6,
    text: "Defender 2. Champion.",
    art: "/art/cards/garen-champ.jpg",
    defender: 2,
    isChampion: true,
  },

  // Jinx deck
  {
    id: "scrapling",
    name: "Zaun Scrapling",
    kind: "unit",
    domains: ["chaos"],
    energy: 1,
    power: 0,
    might: 1,
    text: "A street rat with a pipe and a grudge.",
    art: "/art/cards/scrapling.jpg",
  },
  {
    id: "powpow",
    name: "Pow-Pow",
    kind: "unit",
    domains: ["fury"],
    energy: 2,
    power: 0,
    might: 2,
    text: "Accelerate. Enters ready.",
    art: "/art/cards/powpow.jpg",
    accelerate: true,
  },
  {
    id: "fishbones",
    name: "Fishbones Crew",
    kind: "unit",
    domains: ["fury"],
    energy: 3,
    power: 0,
    might: 3,
    text: "Assault 1.",
    art: "/art/cards/fishbones.jpg",
    assault: 1,
  },
  {
    id: "chompers",
    name: "Flame Chompers",
    kind: "unit",
    domains: ["chaos"],
    energy: 2,
    power: 0,
    might: 2,
    text: "When this dies in combat, deal 1 to an enemy unit here.",
    art: "/art/cards/chompers.jpg",
    deathDamage: 1,
  },
  {
    id: "rocket-girl",
    name: "Rocket Girl",
    kind: "unit",
    domains: ["fury", "chaos"],
    energy: 4,
    power: 1,
    might: 4,
    text: "Ganking. May move battlefield to battlefield.",
    art: "/art/cards/rocket-girl.jpg",
    ganking: true,
  },
  {
    id: "street-demon",
    name: "Street Demons",
    kind: "unit",
    domains: ["chaos"],
    energy: 3,
    power: 0,
    might: 3,
    text: "",
    art: "/art/cards/street-demon.jpg",
  },
  {
    id: "zap",
    name: "Zap!",
    kind: "spell",
    domains: ["fury"],
    energy: 1,
    power: 0,
    text: "Deal 1 damage to a unit.",
    art: "/art/cards/zap.jpg",
    playEffect: { type: "damage", n: 1 },
  },
  {
    id: "excited",
    name: "Get Excited!",
    kind: "spell",
    domains: ["chaos"],
    energy: 2,
    power: 0,
    text: "Draw 2 cards.",
    art: "/art/cards/excited.jpg",
    playEffect: { type: "draw", n: 2 },
  },
  {
    id: "wild-rocket",
    name: "Wild Rocket",
    kind: "spell",
    domains: ["fury"],
    energy: 3,
    power: 0,
    text: "Deal 2 damage to a unit.",
    art: "/art/cards/wild-rocket.jpg",
    playEffect: { type: "damage", n: 2 },
  },
  {
    id: "super-mega",
    name: "Super Mega Death Rocket",
    kind: "spell",
    domains: ["fury", "chaos"],
    energy: 4,
    power: 1,
    text: "Deal 3 damage to a unit.",
    art: "/art/cards/super-mega.jpg",
    playEffect: { type: "damage", n: 3 },
  },
  {
    id: "hex-rockets",
    name: "Hextech Rockets",
    kind: "gear",
    domains: ["fury"],
    energy: 2,
    power: 0,
    text: "Your units have +1 Might.",
    art: "/art/cards/hex-rockets.jpg",
    gearAuraMight: 1,
  },

  // Ahri deck
  {
    id: "disciple",
    name: "Vastayan Disciple",
    kind: "unit",
    domains: ["calm"],
    energy: 1,
    power: 0,
    might: 1,
    text: "",
    art: "/art/cards/disciple.jpg",
  },
  {
    id: "fox-spirit",
    name: "Fox Spirit",
    kind: "unit",
    domains: ["mind"],
    energy: 2,
    power: 0,
    might: 2,
    text: "Accelerate.",
    art: "/art/cards/fox-spirit.jpg",
    accelerate: true,
  },
  {
    id: "ionian-monk",
    name: "Ionian Monk",
    kind: "unit",
    domains: ["calm"],
    energy: 3,
    power: 0,
    might: 3,
    text: "Defender 1.",
    art: "/art/cards/ionian-monk.jpg",
    defender: 1,
  },
  {
    id: "orb-fox",
    name: "Orb of Deception",
    kind: "unit",
    domains: ["mind"],
    energy: 3,
    power: 1,
    might: 3,
    text: "Defender 2.",
    art: "/art/cards/orb-fox.jpg",
    defender: 2,
  },
  {
    id: "spirit-vale",
    name: "Spirit Vale",
    kind: "unit",
    domains: ["calm", "mind"],
    energy: 4,
    power: 0,
    might: 4,
    text: "Ganking.",
    art: "/art/cards/spirit-vale.jpg",
    ganking: true,
  },
  {
    id: "foxfire",
    name: "Fox-Fire",
    kind: "spell",
    domains: ["mind"],
    energy: 1,
    power: 0,
    text: "Deal 1 damage to a unit. Draw 1.",
    art: "/art/cards/foxfire.jpg",
    playEffect: { type: "damage", n: 1 },
  },
  {
    id: "charm",
    name: "Charm",
    kind: "spell",
    domains: ["calm"],
    energy: 2,
    power: 0,
    text: "Return an enemy unit to its owner's base.",
    art: "/art/cards/charm.jpg",
    playEffect: { type: "recall" },
  },
  {
    id: "essence",
    name: "Essence Theft",
    kind: "spell",
    domains: ["mind"],
    energy: 2,
    power: 0,
    text: "Draw 1 card. Ready a rune.",
    art: "/art/cards/essence.jpg",
    playEffect: { type: "draw", n: 1 },
  },
  {
    id: "spirit-rush",
    name: "Spirit Rush",
    kind: "spell",
    domains: ["calm"],
    energy: 3,
    power: 0,
    text: "Ready a friendly unit.",
    art: "/art/cards/spirit-rush.jpg",
    playEffect: { type: "ready_unit" },
  },
  {
    id: "soul-harvest",
    name: "Soul Harvest",
    kind: "spell",
    domains: ["mind"],
    energy: 4,
    power: 1,
    text: "Draw 2 cards.",
    art: "/art/cards/soul-harvest.jpg",
    playEffect: { type: "draw", n: 2 },
  },
  {
    id: "moonstone",
    name: "Moonstone Cache",
    kind: "gear",
    domains: ["mind"],
    energy: 2,
    power: 0,
    text: "When played, draw 1.",
    art: "/art/cards/moonstone.jpg",
    playEffect: { type: "draw", n: 1 },
  },

  // Darius deck
  {
    id: "grunt",
    name: "Noxian Grunt",
    kind: "unit",
    domains: ["fury"],
    energy: 1,
    power: 0,
    might: 2,
    text: "",
    art: "/art/cards/grunt.jpg",
  },
  {
    id: "legionnaire",
    name: "Legionnaire",
    kind: "unit",
    domains: ["order"],
    energy: 2,
    power: 0,
    might: 3,
    text: "",
    art: "/art/cards/legionnaire.jpg",
  },
  {
    id: "brawler",
    name: "Arena Brawler",
    kind: "unit",
    domains: ["fury"],
    energy: 3,
    power: 0,
    might: 4,
    text: "Assault 1.",
    art: "/art/cards/brawler.jpg",
    assault: 1,
  },
  {
    id: "trifarian",
    name: "Trifarian",
    kind: "unit",
    domains: ["order"],
    energy: 4,
    power: 0,
    might: 5,
    text: "",
    art: "/art/cards/trifarian.jpg",
  },
  {
    id: "hand-noxus",
    name: "Hand of Noxus",
    kind: "unit",
    domains: ["fury", "order"],
    energy: 5,
    power: 1,
    might: 6,
    text: "Defender 1.",
    art: "/art/cards/hand-noxus.jpg",
    defender: 1,
  },
  {
    id: "blood-noxus",
    name: "Blood for Noxus",
    kind: "spell",
    domains: ["fury"],
    energy: 1,
    power: 0,
    text: "Deal 1 damage to a unit.",
    art: "/art/cards/blood-noxus.jpg",
    playEffect: { type: "damage", n: 1 },
  },
  {
    id: "apprehend",
    name: "Apprehend",
    kind: "spell",
    domains: ["order"],
    energy: 2,
    power: 0,
    text: "Deal 2 damage to a unit.",
    art: "/art/cards/apprehend.jpg",
    playEffect: { type: "damage", n: 2 },
  },
  {
    id: "decimate",
    name: "Decimate",
    kind: "spell",
    domains: ["fury"],
    energy: 3,
    power: 0,
    text: "Deal 2 damage to each enemy unit at a battlefield.",
    art: "/art/cards/decimate.jpg",
    playEffect: { type: "damage_all_enemy_at", n: 2 },
  },
  {
    id: "dunk",
    name: "Noxian Guillotine",
    kind: "spell",
    domains: ["fury", "order"],
    energy: 4,
    power: 1,
    text: "Deal 4 damage to a unit.",
    art: "/art/spell-rocket.jpg",
    playEffect: { type: "damage", n: 4 },
  },
  {
    id: "banner",
    name: "Noxian Banner",
    kind: "gear",
    domains: ["order"],
    energy: 3,
    power: 0,
    text: "Your units have +1 Might.",
    art: "/art/cards/banner.jpg",
    gearAuraMight: 1,
  },

  // Garen deck
  {
    id: "vanguard",
    name: "Demacian Vanguard",
    kind: "unit",
    domains: ["order"],
    energy: 1,
    power: 0,
    might: 2,
    text: "",
    art: "/art/cards/vanguard.jpg",
  },
  {
    id: "guard",
    name: "Demacian Guard",
    kind: "unit",
    domains: ["body"],
    energy: 2,
    power: 0,
    might: 3,
    text: "Defender 1.",
    art: "/art/cards/guard.jpg",
    defender: 1,
  },
  {
    id: "shield-wall",
    name: "Shield Wall",
    kind: "unit",
    domains: ["order"],
    energy: 2,
    power: 0,
    might: 2,
    text: "Defender 2.",
    art: "/art/cards/shield-wall.jpg",
    defender: 2,
  },
  {
    id: "justice",
    name: "Justice",
    kind: "unit",
    domains: ["body"],
    energy: 3,
    power: 0,
    might: 3,
    text: "Assault 1.",
    art: "/art/unit-demacia.jpg",
    assault: 1,
  },
  {
    id: "silencer",
    name: "Silencer",
    kind: "unit",
    domains: ["body"],
    energy: 3,
    power: 0,
    might: 4,
    text: "",
    art: "/art/unit-demacia.jpg",
  },
  {
    id: "judicator",
    name: "Judicator",
    kind: "unit",
    domains: ["body", "order"],
    energy: 5,
    power: 1,
    might: 6,
    text: "Defender 2.",
    art: "/art/garen.jpg",
    defender: 2,
  },
  {
    id: "courage",
    name: "Courage",
    kind: "spell",
    domains: ["order"],
    energy: 1,
    power: 0,
    text: "A friendly unit gets +2 Might this turn.",
    art: "/art/spell-light.jpg",
    playEffect: { type: "buff", n: 2 },
  },
  {
    id: "rally",
    name: "Rally",
    kind: "spell",
    domains: ["body"],
    energy: 2,
    power: 0,
    text: "Ready a friendly unit.",
    art: "/art/spell-light.jpg",
    playEffect: { type: "ready_unit" },
  },
  {
    id: "judgment",
    name: "Judgment",
    kind: "spell",
    domains: ["body", "order"],
    energy: 4,
    power: 1,
    text: "Deal 4 damage to a unit.",
    art: "/art/spell-light.jpg",
    playEffect: { type: "damage", n: 4 },
  },
  {
    id: "crest",
    name: "Crest of Demacia",
    kind: "gear",
    domains: ["order"],
    energy: 2,
    power: 0,
    text: "When you hold, ready a rune.",
    art: "/art/gear.jpg",
    onHold: { type: "ready_rune" },
  },


  // Champion decks — Viktor, Lee Sin, Annie, Lux
  {
    id: "legend-viktor",
    name: "Viktor, Herald of the Arcane",
    kind: "legend",
    domains: ["mind", "order"],
    energy: 0,
    power: 0,
    text: "Once per turn: put a 1-Might Recruit into your base.",
    art: "/art/viktor.jpg",
    legendAbility: "viktor",
  },
  {
    id: "legend-leesin",
    name: "Lee Sin, Blind Monk",
    kind: "legend",
    domains: ["calm", "body"],
    energy: 0,
    power: 0,
    text: "Once per turn: Exhaust and pay 1 energy. A friendly unit gets +1 Might.",
    art: "/art/leesin.jpg",
    legendAbility: "leesin",
  },
  {
    id: "legend-annie",
    name: "Annie, Dark Child",
    kind: "legend",
    domains: ["fury", "chaos"],
    energy: 0,
    power: 0,
    text: "Once per turn: Exhaust your legend to ready two runes.",
    art: "/art/annie.jpg",
    legendAbility: "annie",
  },
  {
    id: "legend-lux",
    name: "Lux, Lady of Luminosity",
    kind: "legend",
    domains: ["mind", "order"],
    energy: 0,
    power: 0,
    text: "When you cast a spell costing 3 or more, draw 1.",
    art: "/art/lux.jpg",
    legendAbility: "lux",
  },
  {
    id: "viktor-champ",
    name: "Viktor, Innovator",
    kind: "unit",
    domains: ["mind", "order"],
    energy: 5,
    power: 1,
    might: 4,
    text: "Accelerate. Champion.",
    art: "/art/viktor.jpg",
    accelerate: true,
    isChampion: true,
  },
  {
    id: "leesin-champ",
    name: "Lee Sin, Centered",
    kind: "unit",
    domains: ["calm", "body"],
    energy: 6,
    power: 1,
    might: 6,
    text: "Defender 1. Champion.",
    art: "/art/leesin.jpg",
    defender: 1,
    isChampion: true,
  },
  {
    id: "annie-champ",
    name: "Tibbers",
    kind: "unit",
    domains: ["fury", "chaos"],
    energy: 6,
    power: 1,
    might: 7,
    text: "Assault 1. Champion.",
    art: "/art/tibbers.jpg",
    assault: 1,
    isChampion: true,
  },
  {
    id: "lux-champ",
    name: "Lux, Lucent",
    kind: "unit",
    domains: ["mind", "order"],
    energy: 5,
    power: 1,
    might: 4,
    text: "When you conquer, draw 1. Champion.",
    art: "/art/lux.jpg",
    onConquer: { type: "draw", n: 1 },
    isChampion: true,
  },
  {
    id: "recruit",
    name: "Recruit",
    kind: "unit",
    domains: ["order"],
    energy: 0,
    power: 0,
    might: 1,
    text: "Token. Created by Viktor.",
    art: "/art/recruit.jpg",
  },
  {
    id: "eager-apprentice",
    name: "Eager Apprentice",
    kind: "unit",
    domains: ["mind"],
    energy: 1,
    power: 0,
    might: 1,
    text: "",
    art: "/art/recruit.jpg",
  },
  {
    id: "soaring-scout",
    name: "Soaring Scout",
    kind: "unit",
    domains: ["mind"],
    energy: 2,
    power: 0,
    might: 2,
    text: "Accelerate.",
    art: "/art/unit-monk.jpg",
    accelerate: true,
  },
  {
    id: "ravenbloom",
    name: "Ravenbloom Student",
    kind: "unit",
    domains: ["order"],
    energy: 2,
    power: 0,
    might: 2,
    text: "",
    art: "/art/unit-demacia.jpg",
  },
  {
    id: "drummer",
    name: "Noxian Drummer",
    kind: "unit",
    domains: ["order"],
    energy: 3,
    power: 0,
    might: 3,
    text: "When played, ready a rune.",
    art: "/art/unit-noxus.jpg",
    playEffect: { type: "ready_rune" },
  },
  {
    id: "cruel-patron",
    name: "Cruel Patron",
    kind: "unit",
    domains: ["mind"],
    energy: 4,
    power: 0,
    might: 4,
    text: "Defender 1.",
    art: "/art/viktor.jpg",
    defender: 1,
  },
  {
    id: "cull",
    name: "Cull the Weak",
    kind: "spell",
    domains: ["order"],
    energy: 2,
    power: 0,
    text: "Deal 2 damage to a unit.",
    art: "/art/spell-light.jpg",
    playEffect: { type: "damage", n: 2 },
  },
  {
    id: "stupefy",
    name: "Stupefy",
    kind: "spell",
    domains: ["mind"],
    energy: 2,
    power: 0,
    text: "Return an enemy unit to its owner's base.",
    art: "/art/spell-charm.jpg",
    playEffect: { type: "recall" },
  },
  {
    id: "consult",
    name: "Consult the Past",
    kind: "spell",
    domains: ["mind"],
    energy: 2,
    power: 0,
    text: "Draw 1. Ready a rune.",
    art: "/art/spell-charm.jpg",
    playEffect: { type: "draw", n: 1 },
  },
  {
    id: "sprite-call",
    name: "Sprite Call",
    kind: "spell",
    domains: ["order"],
    energy: 1,
    power: 0,
    text: "Put a 1-Might Recruit into your base.",
    art: "/art/recruit.jpg",
    playEffect: { type: "token" },
  },
  {
    id: "hidden-blade",
    name: "Hidden Blade",
    kind: "spell",
    domains: ["order"],
    energy: 1,
    power: 0,
    text: "Deal 1 damage to a unit.",
    art: "/art/spell-light.jpg",
    playEffect: { type: "damage", n: 1 },
  },
  {
    id: "pit-rookie",
    name: "Pit Rookie",
    kind: "unit",
    domains: ["body"],
    energy: 1,
    power: 0,
    might: 2,
    text: "",
    art: "/art/unit-monk.jpg",
  },
  {
    id: "stalwart-poro",
    name: "Stalwart Poro",
    kind: "unit",
    domains: ["calm"],
    energy: 2,
    power: 0,
    might: 2,
    text: "Defender 1.",
    art: "/art/poro.jpg",
    defender: 1,
  },
  {
    id: "first-mate",
    name: "First Mate",
    kind: "unit",
    domains: ["body"],
    energy: 2,
    power: 0,
    might: 3,
    text: "",
    art: "/art/unit-brute.jpg",
  },
  {
    id: "wielder",
    name: "Wielder of Water",
    kind: "unit",
    domains: ["calm"],
    energy: 3,
    power: 0,
    might: 3,
    text: "",
    art: "/art/unit-monk.jpg",
  },
  {
    id: "wildclaw",
    name: "Wildclaw Shaman",
    kind: "unit",
    domains: ["body"],
    energy: 3,
    power: 0,
    might: 4,
    text: "Assault 1.",
    art: "/art/unit-brute.jpg",
    assault: 1,
  },
  {
    id: "discipline",
    name: "Discipline",
    kind: "spell",
    domains: ["calm"],
    energy: 2,
    power: 0,
    text: "A friendly unit gets +2 Might this turn.",
    art: "/art/spell-charm.jpg",
    playEffect: { type: "buff", n: 2 },
  },
  {
    id: "challenge",
    name: "Challenge",
    kind: "spell",
    domains: ["body"],
    energy: 2,
    power: 0,
    text: "Deal 2 damage to a unit.",
    art: "/art/spell-light.jpg",
    playEffect: { type: "damage", n: 2 },
  },
  {
    id: "stand-united",
    name: "Stand United",
    kind: "spell",
    domains: ["calm"],
    energy: 3,
    power: 0,
    text: "A friendly unit gets +2 Might this turn. Ready a rune.",
    art: "/art/spell-charm.jpg",
    playEffect: { type: "buff", n: 2 },
  },
  {
    id: "mystic-poro",
    name: "Mystic Poro",
    kind: "unit",
    domains: ["chaos"],
    energy: 1,
    power: 0,
    might: 1,
    text: "",
    art: "/art/poro.jpg",
  },
  {
    id: "merchant",
    name: "Traveling Merchant",
    kind: "unit",
    domains: ["chaos"],
    energy: 2,
    power: 0,
    might: 2,
    text: "When played, draw 1.",
    art: "/art/unit-zaun.jpg",
    playEffect: { type: "draw", n: 1 },
  },
  {
    id: "deckhand",
    name: "Sneaky Deckhand",
    kind: "unit",
    domains: ["chaos"],
    energy: 2,
    power: 0,
    might: 2,
    text: "Accelerate.",
    art: "/art/unit-zaun.jpg",
    accelerate: true,
  },
  {
    id: "annie-fiery",
    name: "Annie, Fiery",
    kind: "unit",
    domains: ["fury"],
    energy: 4,
    power: 0,
    might: 4,
    text: "Assault 1.",
    art: "/art/annie.jpg",
    assault: 1,
  },
  {
    id: "marauder",
    name: "Maddened Marauder",
    kind: "unit",
    domains: ["fury"],
    energy: 3,
    power: 0,
    might: 4,
    text: "",
    art: "/art/unit-brute.jpg",
  },
  {
    id: "gust",
    name: "Gust",
    kind: "spell",
    domains: ["chaos"],
    energy: 1,
    power: 0,
    text: "Return an enemy unit to its owner's base.",
    art: "/art/spell-charm.jpg",
    playEffect: { type: "recall" },
  },
  {
    id: "incinerate",
    name: "Incinerate",
    kind: "spell",
    domains: ["fury"],
    energy: 2,
    power: 0,
    text: "Deal 2 damage to a unit.",
    art: "/art/spell-rocket.jpg",
    playEffect: { type: "damage", n: 2 },
  },
  {
    id: "disintegrate",
    name: "Disintegrate",
    kind: "spell",
    domains: ["fury"],
    energy: 3,
    power: 0,
    text: "Deal 3 damage to a unit.",
    art: "/art/spell-rocket.jpg",
    playEffect: { type: "damage", n: 3 },
  },
  {
    id: "firestorm",
    name: "Firestorm",
    kind: "spell",
    domains: ["fury", "chaos"],
    energy: 4,
    power: 1,
    text: "Deal 2 damage to each enemy unit at a battlefield.",
    art: "/art/spell-rocket.jpg",
    playEffect: { type: "damage_all_enemy_at", n: 2 },
  },
  {
    id: "light-mage",
    name: "Light Mage",
    kind: "unit",
    domains: ["mind"],
    energy: 1,
    power: 0,
    might: 1,
    text: "",
    art: "/art/lux.jpg",
  },
  {
    id: "prism-guard",
    name: "Prism Guard",
    kind: "unit",
    domains: ["order"],
    energy: 2,
    power: 0,
    might: 2,
    text: "Defender 1.",
    art: "/art/unit-demacia.jpg",
    defender: 1,
  },
  {
    id: "illuminator",
    name: "Illuminator",
    kind: "unit",
    domains: ["mind"],
    energy: 3,
    power: 0,
    might: 3,
    text: "",
    art: "/art/lux.jpg",
  },
  {
    id: "final-spark",
    name: "Final Spark",
    kind: "spell",
    domains: ["mind", "order"],
    energy: 4,
    power: 1,
    text: "Deal 4 damage to a unit.",
    art: "/art/spell-light.jpg",
    playEffect: { type: "damage", n: 4 },
  },
  {
    id: "lucent",
    name: "Lucent Singularity",
    kind: "spell",
    domains: ["mind"],
    energy: 3,
    power: 0,
    text: "Deal 2 damage to a unit. Draw 1.",
    art: "/art/spell-light.jpg",
    playEffect: { type: "damage", n: 2 },
  },
  {
    id: "prismatic",
    name: "Prismatic Barrier",
    kind: "spell",
    domains: ["order"],
    energy: 2,
    power: 0,
    text: "A friendly unit gets +2 Might this turn.",
    art: "/art/spell-light.jpg",
    playEffect: { type: "buff", n: 2 },
  },
  {
    id: "illuminate",
    name: "Illuminate",
    kind: "spell",
    domains: ["mind"],
    energy: 3,
    power: 0,
    text: "Draw 2 cards.",
    art: "/art/spell-light.jpg",
    playEffect: { type: "draw", n: 2 },
  },

  // Battlefields
  {
    id: "dragon",
    name: "Dragon Pit",
    kind: "battlefield",
    domains: [],
    energy: 0,
    power: 0,
    text: "When you conquer here, deal 1 to an enemy unit here if any remain.",
    art: "/art/bf-dragon.jpg",
    onConquer: { type: "damage", n: 1 },
  },
  {
    id: "baron",
    name: "Baron Pit",
    kind: "battlefield",
    domains: [],
    energy: 0,
    power: 0,
    text: "Units here have +1 Might.",
    art: "/art/bf-baron.jpg",
    bfBonusMight: 1,
  },
  {
    id: "abyss",
    name: "Howling Abyss",
    kind: "battlefield",
    domains: [],
    energy: 0,
    power: 0,
    text: "When you conquer here, draw 1.",
    art: "/art/bf-abyss.jpg",
    onConquer: { type: "draw", n: 1 },
  },
  {
    id: "nexus",
    name: "The Nexus",
    kind: "battlefield",
    domains: [],
    energy: 0,
    power: 0,
    text: "When you hold here, ready a rune.",
    art: "/art/bf-nexus.jpg",
    onHold: { type: "ready_rune" },
  },
];

export const CARD_BY_ID: Record<string, CardDef> = Object.fromEntries(
  CARDS.map((c) => [c.id, c]),
);

export function getDef(id: string): CardDef {
  const d = CARD_BY_ID[id];
  if (!d) throw new Error(`Unknown card ${id}`);
  return d;
}

export function getLegend(id: string): LegendInfo {
  const l = LEGENDS.find((x) => x.id === id);
  if (!l) throw new Error(`Unknown legend ${id}`);
  return l;
}

const DECK_LISTS: Record<string, [string, number][]> = {
  jinx: [
    ["scrapling", 3],
    ["powpow", 3],
    ["fishbones", 3],
    ["chompers", 2],
    ["rocket-girl", 2],
    ["street-demon", 3],
    ["zap", 3],
    ["excited", 2],
    ["wild-rocket", 2],
    ["super-mega", 2],
    ["hex-rockets", 2],
  ],
  ahri: [
    ["disciple", 3],
    ["fox-spirit", 3],
    ["ionian-monk", 3],
    ["orb-fox", 2],
    ["spirit-vale", 2],
    ["foxfire", 3],
    ["charm", 3],
    ["essence", 2],
    ["spirit-rush", 2],
    ["soul-harvest", 2],
    ["moonstone", 2],
  ],
  darius: [
    ["grunt", 3],
    ["legionnaire", 3],
    ["brawler", 3],
    ["trifarian", 3],
    ["hand-noxus", 2],
    ["blood-noxus", 3],
    ["apprehend", 3],
    ["decimate", 2],
    ["dunk", 2],
    ["banner", 2],
  ],
  garen: [
    ["vanguard", 3],
    ["guard", 3],
    ["shield-wall", 3],
    ["justice", 3],
    ["silencer", 3],
    ["judicator", 2],
    ["courage", 3],
    ["rally", 2],
    ["judgment", 2],
    ["crest", 2],
  ],
  viktor: [
    ["eager-apprentice", 3],
    ["soaring-scout", 3],
    ["ravenbloom", 3],
    ["drummer", 3],
    ["cruel-patron", 2],
    ["cull", 3],
    ["stupefy", 2],
    ["consult", 2],
    ["sprite-call", 3],
    ["hidden-blade", 2],
    ["moonstone", 2],
  ],
  leesin: [
    ["pit-rookie", 3],
    ["stalwart-poro", 3],
    ["first-mate", 3],
    ["wielder", 3],
    ["wildclaw", 2],
    ["charm", 2],
    ["discipline", 3],
    ["challenge", 3],
    ["stand-united", 2],
    ["rally", 2],
    ["crest", 2],
  ],
  annie: [
    ["mystic-poro", 3],
    ["merchant", 3],
    ["deckhand", 3],
    ["annie-fiery", 2],
    ["marauder", 3],
    ["chompers", 2],
    ["gust", 3],
    ["incinerate", 3],
    ["disintegrate", 2],
    ["firestorm", 2],
    ["zap", 2],
  ],
  lux: [
    ["light-mage", 3],
    ["prism-guard", 3],
    ["illuminator", 3],
    ["guard", 3],
    ["vanguard", 2],
    ["final-spark", 2],
    ["lucent", 3],
    ["prismatic", 3],
    ["illuminate", 2],
    ["courage", 2],
    ["crest", 2],
  ],
};

export function deckListFor(legendId: string): [string, number][] {
  return DECK_LISTS[legendId] ?? DECK_LISTS.jinx;
}
